# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  flutter_tests:
    name: Flutter analyze and Test
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x

      - name: Run Flutter Pub Get
        run: flutter pub get

      - name: Check Code Formatting - lib
        run: dart format --set-exit-if-changed lib/

      - name: Check Code Formatting - test
        run: dart format --set-exit-if-changed test/

      # TODO: When finished the features, able the tests
      - name: Run Tests
        run: flutter test --coverage

      - name: Verify if passed in the minimum percent
        uses: VeryGoodOpenSource/very_good_coverage@v3.0.0
        with:
          min_coverage: 85