# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  flutter_tests:
    name: Flutter analyze and Test
    runs-on: macos-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3.9.0
        with:
          java-version: "11.x"
          distribution: "temurin"

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2.8.0
        with:
          channel: "stable"

      - name: Run Flutter Pub Get
        run: flutter pub get

      - name: Run Flutter Analyze
        run: flutter analyze

      - name: Check Code Formatting - lib
        run: dart format -l "100" --set-exit-if-changed lib/

      - name: Check Code Formatting - test
        run: dart format -l "100" --set-exit-if-changed test/

      # TODO: When finished the features, able the tests
      - name: Run Tests
        run: flutter test --coverage

      - name: Verify if passed in the minimum percent
        uses: VeryGoodOpenSource/very_good_coverage@v2.1.0
        with:
          min_coverage: 85